const toggle=document.querySelector('.nav-toggle');
const nav=document.querySelector('#navigation');
function closeNav(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation')}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeNav));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNav()});
const menus={day:{image:'assets/dining.jpg',alt:'Mulan’s Birkenhead dining room',caption:'A LITTLE COMFORT, ANY TIME OF DAY',eyebrow:'THE GOOD OLD DAYS',title:'Comfort food.<br>Fresh perspective.',description:'Your familiar breakfast favourites meet vibrant Southeast Asian flavours. Settle in for a slow morning or make a lunch of it.',links:[['Breakfast & brunch menu','https://mulan.co.nz/wp-content/uploads/2026/08/Mulan-Brunch-Menu-28JULY2026-OP.pdf']]},night:{image:'assets/food-1.jpg',alt:'Malaysian curry with rice',caption:'BIG FLAVOURS. WARM MEMORIES.',eyebrow:'A TASTE OF PENANG',title:'Homestyle cooking.<br>Wholehearted flavour.',description:'Evenings bring the comforting flavours of Chef James’s Malaysian roots to the table. Explore our à la carte selection, with a dedicated vegan menu too.',links:[['Dinner à la carte','https://mulan.co.nz/wp-content/uploads/2025/11/Mulan-Dinner-Menu-Final.pdf'],['Vegan dinner menu','https://mulan.co.nz/wp-content/uploads/2025/11/Mulan-Vegan-Menu-Final.pdf']]},sharing:{image:'assets/hero.png',alt:'A spread of Mulan dishes for a shared meal',caption:'GOOD COMPANY. ONE GENEROUS TABLE.',eyebrow:'BETTER TOGETHER',title:'More dishes.<br>More memories.',description:'Gather your favourite people for a Malaysian banquet. For groups of 8–10, a sharing feast is encouraged. For groups over 10, call our team to arrange your banquet.',links:[['Explore the banquet menu','https://mulan.co.nz/wp-content/uploads/2025/12/Mulan-Banquet-Menu-web_251204_114645.pdf'],['Talk to us about your gathering','mailto:bookings@mulan.co.nz']]}};
const tabs=[...document.querySelectorAll('[data-menu]')];
function selectMenu(key){const m=menus[key];tabs.forEach(t=>{const selected=t.dataset.menu===key;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1});document.querySelector('#menu-panel').setAttribute('aria-labelledby',key+'-tab');const img=document.querySelector('#menu-photo');img.src=m.image;img.alt=m.alt;document.querySelector('#menu-image-caption').textContent=m.caption;document.querySelector('#menu-eyebrow').textContent=m.eyebrow;document.querySelector('#menu-title').innerHTML=m.title;document.querySelector('#menu-description').textContent=m.description;document.querySelector('#menu-links').replaceChildren(...m.links.map(([title,url])=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=title;const s=document.createElement('span');s.textContent='↗';a.append(s);return a}))}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectMenu(t.dataset.menu));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].focus();selectMenu(tabs[next].dataset.menu)}})});
document.querySelectorAll('[data-pick]').forEach(a=>a.addEventListener('click',()=>selectMenu(a.dataset.pick)));
const dialog=document.querySelector('.lightbox');
document.querySelectorAll('[data-photo]').forEach(button=>button.addEventListener('click',()=>{dialog.querySelector('img').src=button.dataset.photo;dialog.querySelector('img').alt=button.querySelector('img').alt;dialog.showModal()}));
dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelector('#year').textContent=new Date().getFullYear();
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.welcome,.section-heading,.story-copy,.local>h2,.visit>div').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
